### PR TITLE
Feature: generify dynamic JPA query templates by creating a main abstraction

### PR DESCRIPTION
**Pull request by jeansossmeier**
In order to keep this implementation more flexible, this is an implementation to enable multiple template providers.
There's is also minor fix for postgres type casting in queries and a rollback from using commons into the same project.

### CODE REVIEW

**Comment by joutvhu** [comment]
Sound good. However the commons package should be moved to [spring-dynamic-commons](https://github.com/joutvhu/spring-dynamic-commons)

**Comment by jeansossmeier** [comment]
Great, thank you! I just felt like the whole commons was an "over" thing after I have resignified a few things and the commons ended up with 3-4 files, ended up looking like it had no purpose.

This module plus an external module for each template implementation looks like a decent approach, what do you think?

`com.github.joutvhu:spring-dynamic-jpa`
`com.github.joutvhu:spring-dynamic-jpa-freemarker`
`com.github.joutvhu:spring-dynamic-jpa-handlebars`

Anyway, just a thought or two, don't mean to intrude.
Thanks :D

**Comment by joutvhu** [comment]
[spring-dynamic-commons](https://github.com/joutvhu/spring-dynamic-commons) is decoupled for general use for [spring-dynamic-r2dbc](https://github.com/joutvhu/spring-dynamic-r2dbc) and spring-dynamic-jpa.

The implementations should be separated as follows:

- spring-dynamic-commons
- spring-dynamic-jpa
- spring-dynamic-r2dbc
- spring-dynamic-freemarker
- spring-dynamic-handlebars

To use, the user will combine them, for example:

- spring-dynamic-commons
- spring-dynamic-jpa
- spring-dynamic-freemarker

Or:

- spring-dynamic-commons
- spring-dynamic-r2dbc
- spring-dynamic-handlebars

...

**Comment by jeansossmeier** [comment]
Hey there! Sounds good, I will tackle this ASAP when I have some extra time this week.
Should be pretty straightforward.

**Comment by jeansossmeier** [comment]
Sorry for the delay, I've pushed some changes you asked me to commons and this project.
Please let me know what you think.

**Pull request merged**
